name = "CondensedMatterSOS"
uuid = "676dea7e-7535-42cf-a5c4-14732a6b7aba"
authors = ["Benoît Legat <benoit.legat@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "0.17.15"
MultivariatePolynomials = "0.3.7"
